/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author JOFRAN
 */
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class RegistroPrestamo extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs =null;
PreparedStatement pat=null;
    /**
     * Creates new form RegistroPrestamo
     */
    public RegistroPrestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Salir = new javax.swing.JButton();
        jLabel1Prestamos = new javax.swing.JLabel();
        jLabel1BuscarEstudiante = new javax.swing.JLabel();
        jButton1RegistrarPrestamo = new javax.swing.JButton();
        jTextField1Buscarestudiante = new javax.swing.JTextField();
        jButton1Buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Salir.setBackground(new java.awt.Color(0, 153, 0));
        jButton1Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1Salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Salir.setText("Salir");
        jButton1Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel1Prestamos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1Prestamos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Prestamos.setText("Sistema de Prestamos de libros");
        getContentPane().add(jLabel1Prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1BuscarEstudiante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1BuscarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1BuscarEstudiante.setText("Buscar Estudiante");
        getContentPane().add(jLabel1BuscarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, -1));

        jButton1RegistrarPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        jButton1RegistrarPrestamo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1RegistrarPrestamo.setText("Registrar Prestamo");
        jButton1RegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RegistrarPrestamoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1RegistrarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 170, -1));
        getContentPane().add(jTextField1Buscarestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 30));

        jButton1Buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1Buscar.setText("Buscar");
        jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 110, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 500, 170));

        jLabel1Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abe8f59dde6b65fe834fe95caa8c34fd.jpg"))); // NOI18N
        jLabel1Fondo.setText("jLabel1");
        getContentPane().add(jLabel1Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1SalirActionPerformed

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1BuscarActionPerformed

    private void jButton1RegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RegistrarPrestamoActionPerformed
        Prestamo x = new Prestamo();
        x.setVisible(true);
    }//GEN-LAST:event_jButton1RegistrarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*et the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Conexion con=new Conexion();
        con.conectar();
        con.cerrrarConexion();
        
        java.awt.EventQueue.invokeLater(() -> {
            new RegistroPrestamo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JButton jButton1RegistrarPrestamo;
    private javax.swing.JButton jButton1Salir;
    private javax.swing.JLabel jLabel1BuscarEstudiante;
    private javax.swing.JLabel jLabel1Fondo;
    private javax.swing.JLabel jLabel1Prestamos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1Buscarestudiante;
    // End of variables declaration//GEN-END:variables
}
